<a href="https://colab.research.google.com/github/Sri190/Machine-Learning-Projects--Youtube/blob/main/ML_Project%3D19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
#Import All The Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder,StandardScaler
from imblearn.over_sampling import SMOTE
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import warnings
warnings.filterwarnings('ignore')

#Load The Dataset
df=pd.read_csv('/content/WA_Fn-UseC_-Telco-Customer-Churn.csv')

#Data Preprocessing
df.drop('customerID',axis=1,inplace=True)
df['TotalCharges']=df['TotalCharges'].replace({" ":"0.0"})
df['TotalCharges']=df['TotalCharges'].astype(float)
object_cols = df.select_dtypes(include='object').columns.to_list()
object_cols = ['SeniorCitizen']+object_cols
df[object_cols] = df[object_cols].apply(LabelEncoder().fit_transform)
scalar=StandardScaler()
X=df.drop('Churn',axis=1)
x=scalar.fit_transform(X)
y=df['Churn']

#Train-Test Split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
smote = SMOTE(random_state=42)
x_train, y_train = smote.fit_resample(x_train, y_train)

#Model Evaluation
model={"Decision Tree":DecisionTreeClassifier(random_state=42),"Random Forest":RandomForestClassifier(random_state=42),"XGBoost":XGBClassifier(random_state=42)}
cv_scores = {}
for model_name, model in model.items():
    print("******************************")
    print("Model Name: ",model_name)
    print("******************************")
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)
    print("Accuracy Score: ",accuracy_score(y_test, y_pred))
    print("Confusion Matrix: \n",confusion_matrix(y_test, y_pred))

******************************
Model Name:  Decision Tree
******************************
Accuracy Score:  0.7352732434350603
Confusion Matrix: 
 [[829 207]
 [166 207]]
******************************
Model Name:  Random Forest
******************************
Accuracy Score:  0.7892122072391767
Confusion Matrix: 
 [[887 149]
 [148 225]]
******************************
Model Name:  XGBoost
******************************
Accuracy Score:  0.7771469127040455
Confusion Matrix: 
 [[884 152]
 [162 211]]
